### ISSUE TITLE
Add authorization and authentication module

### ISSUE THREAD

**Issue by dzikus13** [dzikus13/shooting-club#2]

**Comment by dzikus13** [comment]
I would like to see a login page. Additionally main template should display username
Also there will be registration pags.

**Comment by bamil0** [comment]
we have a problem with authentication module - with signing up to be more specific. we have this kind of error and we don't really know what to do with it:

![notitle](https://user-images.githubusercontent.com/106228974/189873028-f0ac1a70-043c-4c2b-af2a-c443e94a0bfa.png)

**Comment by rs-piotr-kryska** [comment]
It seems that you have configured some ways of authentication and it cannot be used.
Please check the configuration of ALLAUTH

**Comment by bamil0** [comment]
we've made the login and authorization system, we need to add the csrf token for it to work properly but i think it's fair to say we're close to ending this task
![image](https://user-images.githubusercontent.com/106228974/190340490-6bab6b8e-d2be-4ef0-8029-6e02df161bbc.png)
